name: Build Python package
run-name: ${{ github.actor }} is building the Python package

# Run job by triggering it manually with the web UI: https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow#running-a-workflow
on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  build:
    name: Build Python package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user

      - name: Build a binary wheel and a source tarball
        run: >-
          python3 -m
          build
          --sdist
          --wheel
          --outdir dist/

      - uses: actions/upload-artifact@v3
        with:
          name: release-build
          path: dist/